config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  root "welcome#index"
  
  get "/auth/:provider/callback" => "sessions#create"
  get "/signout" => "sessions#destroy"
  
  get "/search", to: "search#index", as: :search
  resources :reality_check, only: [:index]
  resources :listings, only: [:show] do
    post 'reality_check', on: :member
  end
  resources :users, only: [:show]

  get 'geocoder/city_from_location'

  mount RailsPerformance::Engine, at: 'rails/performance'

  resources :favorites, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  validates_presence_of :name
  validates_presence_of :email

  def self.from_omniauth(response)
    User.find_or_create_by(uid: response[:uid], provider: response[:provider]) do |u|
      u.name = response[:info][:name]
      u.email = response[:info][:email]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    return unless session[:user_id]

    @_current_user ||= User.find_by(id: session[:user_id])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    if current_user.present? && params[:favorite] == "true"
      user_id = current_user.id.to_s
      listing_id = params[:id]

      service = OomprBeService.new
      service.new_favorite(user_id, listing_id)
    else
      redirect_to '/auth/google_oauth2'
    end
  end

  def destroy
    service = OomprBeService.new
    service.delete_favorite(params[:fav_id])
    redirect_to user_path(current_user)
  end
end

app/controllers/geocoder_controller.rb
class GeocoderController < ApplicationController

  def city_from_location
    latitude = params[:latitude]
    longitude = params[:longitude]
    api_key = Rails.application.credentials.geocoder[:key]
    url = "https://api.opencagedata.com/geocode/v1/json?q=#{latitude}+#{longitude}&key=#{api_key}"

    response = Net::HTTP.get(URI(url))
    data = JSON.parse(response)

    if data['results'] && data['results'].any?
      city = data['results'][0]['components']['city'] ||
             data['results'][0]['components']['town'] ||
             data['results'][0]['components']['village']
      render json: { city: city || 'City not found' }
    else
      render json: { error: 'City not found' }, status: :not_found
    end
  rescue StandardError => e
    logger.error "Error fetching city data: #{e.message}"
    render json: { error: 'Unable to retrieve city' }, status: :internal_server_error
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  def show
    @listing = fetch_listing(listing_params[:id])
  end

  def reality_check
    cookies[:monthly] = {
      value: params[:monthly],
      expires: 24.hours.from_now
    }

    required_income = fetch_required_income(listing_params[:id])

    cookies[:required_income] = {
      value: required_income,
      expires: 24.hours.from_now
    }
    
    # Set a flash message to indicate that the modal should be shown
    flash[:show_modal] = true
    
    redirect_to listing_path(params[:id])
  end

  private

  def fetch_listing(listing_id)
    cache_key = "listing_#{listing_id}"
    Rails.cache.fetch(cache_key, expires_in: 12.hours) do
      OomprBeFacade.new.get_listing_by_id(listing_id)
    end
  end

  def fetch_required_income(listing_id)
    cache_key = "required_income_#{listing_id}"
    Rails.cache.fetch(cache_key, expires_in: 24.hours) do
      OomprBeFacade.new.required_monthly_income(listing_id)
    end
  end

  def listing_params
    params.permit(:id)
  end
end

app/controllers/reality_check_controller.rb
class RealityCheckController < ApplicationController
  def index
    city = cookies[:city]
    cookies[:monthly] = {
      value: params[:monthly],
      expires: 24.hours.from_now
    }
    monthly_income = cookies[:monthly]

    @rc_listings = fetch_reality_check(city, monthly_income)
  end

  private

  def fetch_reality_check(city, monthly_income)
    cache_key = "reality_check_#{city}_#{monthly_income}"
    Rails.cache.fetch(cache_key, expires_in: 12.hours) do
      OomprBeFacade.new.reality_check(city, monthly_income)
    end
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    cookies[:city] = {
      value: search_params[:city],
      expires: 24.hours.from_now
    }
    city = cookies[:city]

    @listings = Kaminari.paginate_array(fetch_listings_by_city(city)).page(params[:page]).per(3)

    if @listings.empty?
      flash[:notice] = "No listings found. Please try again."
      redirect_to root_path
    end
  end

  private

  def search_params
    params.permit(:city)
  end

  def fetch_listings_by_city(city)
    cache_key = "search_listings_by_city_#{city}"
    Rails.cache.fetch(cache_key, expires_in: 12.hours) do
      OomprBeFacade.new.search_listings_by_city(city)
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    Rails.logger.info "WE GET HERE #{request.env["omniauth.auth"]}" 
    #inside of request.env["omniauth.auth"]["info"] we have name email 
    #inside of request.env["omniauth.auth"]["provider"] we have name of the provider 
    user = User.from_omniauth(request.env['omniauth.auth'])

    if user.valid?
      session[:user_id] = user.id
      redirect_to user_path(user)
    else 
      flash[:notice] = "Must create account first"
      User.create!(user_params)
      session[:user_id] = user.id
      redirect_to '/'

    end
  end


  def new
  end

  def destroy
    session.destroy
    redirect_to "/"
  end

  private 

  def user_params
    params.permit(:name, :email)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    facade = OomprBeFacade.new
    @favorites = facade.get_all_favorites_for_user(current_user.id)
  end

  private

  # def fetch_favorites_for_user(current_user.id)
  #   cache_key = "get_all_favorites_for_user_#{current_user.id}"
  #   Rails.cache.fetch(cache_key, expires_in: 12.hours) do
  #     OomprBeFacade.new.get_all_favorites_for_user(current_user.id)
  #   end
  # end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <% unless type == "show_modal" %>
    <div class="flash <%= type %>">
      <%= message %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<div class="header-container d-flex justify-content-end align-items-center bg-danger text-white p-3">
  <div class="d-flex align-items-center">
    <% if current_user.present? %>
      <%= link_to 'Log Out', '/signout', class: 'btn btn-outline-light me-2' %>
      <span><%= link_to current_user.name, user_path(current_user), class: 'white-link' %></span>
    <% else %>
      <%= link_to 'Log In', '/auth/google_oauth2', class: 'btn btn-outline-light' %>
    <% end %>
  </div>
</div>

    
<html>
  <head>
    <title>OomprFrontend</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <!-- Custom CSS -->
    <%= stylesheet_link_tag 'custom', media: 'all', 'data-turbolinks-track': 'reload' %>

    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">

    <!-- Fancybox CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css" rel="stylesheet">
    <%= hotwire_livereload_tags if Rails.env.development? %>
  </head>

  <body>
    <%= render 'layouts/flash_messages' %>
    <%= yield %>

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <!-- Fancybox JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js"></script>

    <!-- Initialize Fancybox -->
    <script>
      $(document).on('turbolinks:load', function() {
        $('[data-fancybox="gallery"]').fancybox({
          // Add any custom options here
        });
      });
    </script>

    <! -- Auto Scroll to Form -->
    <script>
      document.addEventListener("DOMContentLoaded", function() {
        var collapseElement = document.getElementById('incomeFormContainer');
        var realityCheckButton = document.querySelector('.reality-check-btn');

        realityCheckButton.addEventListener('click', function() {
          $(collapseElement).on('shown.bs.collapse', function() {
          collapseElement.scrollIntoView({ behavior: 'smooth', block: 'start' });
          $(collapseElement).off('shown.bs.collapse'); // Unbind the event after it's fired
          });
        });
      });
    </script>

    <!-- Favorite Icon -->
    <script>
      document.addEventListener("DOMContentLoaded", function() {
        var favoriteIcons = document.querySelectorAll('.favorite-icon');

        favoriteIcons.forEach(function(icon) {
          icon.addEventListener('click', function(event) {
            event.preventDefault();
            var heartIcon = this.querySelector('i');
            var isFavorite = this.getAttribute('data-favorite') === 'true';

            if (isFavorite) {
              heartIcon.classList.remove('fas');
              heartIcon.classList.add('far');
              this.setAttribute('data-favorite', 'false');
            } else {
              heartIcon.classList.remove('far');
              heartIcon.classList.add('fas');
              this.setAttribute('data-favorite', 'true');
            }
          });
        });
      });
    </script>

    <!-- Inline JavaScript to Show Modal if Flash is Present -->
    <% if flash[:show_modal] %>
      <script type="text/javascript">
      document.addEventListener("DOMContentLoaded", function() {
        var resultModal = new bootstrap.Modal(document.getElementById('resultModal'));
        resultModal.show();
      });
    </script>
  <% end %>

    <!-- Bootstrap JS and dependencies -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
  </body>
</html>

app/views/listings/show.html.erb
<div class="container container-custom text-center">
  <h1 class="oompr-title"><%= link_to 'oompr', root_path, class: 'oompr-title-link' %></h1>
  <div class="row justify-content-center">
    <div class="col-md-10">
      <div class="card mb-4">
        <div class="row no-gutters">
          <div class="col-md-8">
            <div class="row">
              <div class="photos">
                <div class="col-12 mb-2">
                  <a href="<%= @listing.photos.first %>" data-fancybox="gallery" data-caption="Main Photo">
                    <%= image_tag @listing.photos.first, class: 'img-fluid', alt: 'Listing Image' %>
                  </a>
                </div>
                <% @listing.photos[1..3].each do |photo_url| %>
                  <div class="col-6 mb-2">
                    <a href="<%= photo_url %>" data-fancybox="gallery" data-caption="Additional Photo">
                      <%= image_tag photo_url, class: 'img-fluid', alt: 'Listing Image' %>
                    </a>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="card-body position-relative">
              <div class="price">
                <h5 class="card-title"><%= number_to_currency(@listing.price) %></h5>
              </div>
              <div class="listing-info">
                <p class="card-text"><%= @listing.address %></p>
                <div class="d-flex justify-content-around mb-3">
                  <span><i class="fas fa-bed"></i> <%= @listing.bedrooms %></span>
                  <span><i class="fas fa-bath"></i> <%= @listing.bathrooms %></span>
                  <span><i class="fas fa-expand-arrows-alt"></i> <%= @listing.sqft %> ft² </span>
                </div>
              </div>
              <div>
              <%= form_with url: favorites_path, method: :post, local: true, id: 'favorite-form' do %>
                <%= hidden_field_tag :favorite, 'false', id: 'favorite-field' %>
                <%= hidden_field_tag :id, @listing.id %>
                <a href="#" class="position-absolute favorite-icon" 
                   data-favorite="" 
                   style="top: 10px; right: 10px;"
                   onclick="toggleFavorite(event);">
                  <i class="far fa-heart" style="font-size: 28px; color: red;"></i>
                </a>
                <%= submit_tag 'Update Favorite', style: 'display: none;' %>
              <% end %>
              
              <script>
                function toggleFavorite(event) {
                  event.preventDefault(); // Prevent the default anchor behavior
                  var favoriteField = document.getElementById('favorite-field');
                  var currentValue = favoriteField.value;
                  favoriteField.value = currentValue === 'true' ? 'false' : 'true';
                  document.getElementById('favorite-form').submit(); // Submit the form
                }
              </script>              
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Button -->
  <div class="rc-button">
    <button type="button" class="btn btn-danger btn-lg reality-check-btn" data-toggle="collapse" data-target="#incomeFormContainer" aria-expanded="false" aria-controls="incomeFormContainer" data-turbolinks="false">Reality Check</button>
  </div>

  <!-- Collapsible Form -->
  <div class="collapse" id="incomeFormContainer" style="margin-top: 20px;">
    <div class="card card-body">
      <%= form_with url: reality_check_listing_path(@listing.id), method: :post, local: true, id: 'incomeForm', data: {turbo:false} do |form| %>
        <div class="form-group">
          <%= form.label :monthly, "Enter your monthly income:" %>
          <%= form.number_field :monthly, class: "form-control-sm", required: true, min: 0, value: cookies[:monthly] %>
        </div>
        <%= form.submit "Submit", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>

  <!-- Modal -->
  <div class="modal fade" id="resultModal" tabindex="-1" role="dialog" aria-labelledby="resultModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="resultModalLabel">Result</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>What You Make: <%= number_to_currency(cookies[:monthly]) %></p>
          <p>What You Would Need To Make: <%= number_to_currency(cookies[:required_income]) %></p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/reality_check/index.html.erb
<div class="container container-custom">
  <h1 class="oompr-title"><%= link_to 'oompr', root_path, class: 'oompr-title-link' %></h1>
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="listings-container">
        <% if @rc_listings.empty? %>
          <div class="alert alert-warning" role="alert">
            No listings found. Want to search for rentals in your area?
          </div>
        <% else %>
          <% @rc_listings.each do |listing| %>
            <div class="listing-item">
              <div class="card card-custom mb-4">
                <%= link_to listing_path(listing.id), class: "stretched-link text-decoration-none" do %>
                  <div id="carousel<%= listing.id %>" class="carousel slide" data-interval="false">
                    <div class="carousel-inner">
                      <div class="photos">
                        <% listing.photos.each_with_index do |photo_url, index| %>
                          <div class="carousel-item <%= 'active' if index == 0 %>">
                            <%= image_tag photo_url, class: 'd-block w-100', alt: 'Listing Image' %>
                          </div>
                        <% end %>
                      </div>
                    </div>
                    <a class="carousel-control-prev" href="#carousel<%= listing.id %>" role="button" data-slide="prev">
                      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                      <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carousel<%= listing.id %>" role="button" data-slide="next">
                      <span class="carousel-control-next-icon" aria-hidden="true"></span>
                      <span class="sr-only">Next</span>
                    </a>
                  </div>
                  <div class="card-body">
                    <div class="price">
                      <h5 class="card-title"><%= number_to_currency(listing.price) %></h5>
                    </div>
                    <div class="listing-info">
                      <p class="card-text"><%= listing.address %></p>
                      <p class="card-text">
                        <i class="fas fa-bed"></i> <%= listing.bedrooms %>
                        <i class="fas fa-bath"></i> <%= listing.bathrooms %>
                        <i class="fas fa-expand-arrows-alt"></i> <%= listing.sqft %> ft²
                      </p>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/search/index.html.erb
<div class="container container-custom">
  <h1 class="oompr-title"><%= link_to 'oompr', root_path, class: 'oompr-title-link' %></h1>
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="listings-container">
        <% @listings.each do |listing| %>
          <% cache ["listing", listing] do %>
            <div class="listing-item">
              <div class="card card-custom mb-4">
                <%= link_to listing_path(listing.id), class: "stretched-link text-decoration-none" do %>
                  <div id="carousel<%= listing.id %>" class="carousel slide" data-interval="false">
                    <div class="carousel-inner">
                      <div class="photos">
                        <% listing.photos.each_with_index do |photo_url, index| %>
                          <div class="carousel-item <%= 'active' if index == 0 %>">
                            <%= image_tag photo_url, class: 'd-block w-100', alt: 'Listing Image' %>
                          </div>
                        <% end %>
                      </div>
                    </div>
                    <a class="carousel-control-prev" href="#carousel<%= listing.id %>" role="button" data-slide="prev">
                      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                      <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carousel<%= listing.id %>" role="button" data-slide="next">
                      <span class="carousel-control-next-icon" aria-hidden="true"></span>
                      <span class="sr-only">Next</span>
                    </a>
                  </div>
                  <div class="card-body">
                    <div class="price">
                      <h5 class="card-title"><%= number_to_currency(listing.price) %></h5>
                    </div>
                    <div class="listing-info">
                      <p class="card-text"><%= listing.address %></p>
                      <p class="card-text">
                        <i class="fas fa-bed"></i> <%= listing.bedrooms %>
                        <i class="fas fa-bath"></i> <%= listing.bathrooms %>
                        <i class="fas fa-expand-arrows-alt"></i> <%= listing.sqft %> ft²
                      </p>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>

    <div class="container">
      <div class="d-flex justify-content-center">
        <%= paginate @listings %>
      </div>
    </div>


  </div>


  <!-- Button -->
  <div class="rc-button">
    <button type="button" class="btn btn-danger btn-lg reality-check-btn" data-toggle="collapse" data-target="#incomeFormContainer" aria-expanded="false" aria-controls="incomeFormContainer" data-turbolinks="false">Reality Check</button>
  </div>

  <!-- Collapsible Form -->
  <div class="collapse" id="incomeFormContainer" style="margin-top: 20px;">
    <div class="card card-body">
      <%= form_with url: reality_check_index_path, method: :get, local: true do |form| %>
        <div class="form-group">
          <%= form.label :monthly, "Enter your monthly income:" %>
          <%= form.number_field :monthly, class: "form-control-sm", required: true, min: 0 %>
        </div>
        <%= form.submit "Submit", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container container-custom">
  <h1 class="oompr-title">
    <%= link_to 'oompr', root_path, class: 'oompr-title-link' %>
  </h1>
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="user-info">
        <h2 class="user-name"><%= current_user.name %></h2>
        <h3 class="saved-listings">Saved Listings</h3>
      </div>
      <div class="listings-container">
        <% if @favorites.empty? %>
          <div class="no-favorites">
            <p>You have no saved listings.</p>
          </div>
        <% else %>
          <% @favorites.each do |favorite| %>
            <% cache ["favorite", favorite] do %>
              <div class="listing-item listing-item-<%= favorite.id %>">
                <div class="card card-custom mb-0"> <!-- Remove bottom margin -->
                  <%= link_to listing_path(favorite.listing_id), class: "stretched-link text-decoration-none" do %>
                    <div class="listing-content d-flex align-items-start">
                      <div class="image-container">
                        <%= image_tag favorite.picture, class: 'img-large', alt: 'Listing Image' %>
                      </div>
                      <div class="text-info ml-3">
                        <div class="price">
                          <h5 class="card-title"><%= number_to_currency(favorite.price) %></h5>
                        </div>
                        <div class="listing-info">
                          <p class="card-text"><%= favorite.address %></p>
                        </div>
                      </div>
                    </div>
                  <% end %>
                </div>
                <%= form_with url: favorite_path(favorite), method: :delete, local: true, class: 'delete-form' do |form| %>
                  <%= hidden_field_tag :fav_id, favorite.id %> 
                  <%= submit_tag 'Remove', class: 'btn btn-danger btn-block' %>
                <% end %>
              </div>
            <% end %>
            <br><br>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="container-fluid vh-100 d-flex flex-column justify-content-center align-items-center text-center bg-danger">
  <div class="w-100">
    <h1 class="text-white display-3">oompr</h1>
    <h3 class="text-white mb-4">Where do you want to live?</h3>
    <%= form_tag(search_path, method: :get, class: "w-50 mx-auto") do %>
      <div class="input-group mb-3">
        <span class="input-group-text"><i class="fas fa-search"></i></span>
        <%= text_field_tag :city, nil, placeholder: "Enter a city...", class: "form-control" %>
        <button class="btn btn-outline-light" type="submit">Search</button>
      </div>
    <% end %>
    <button id="useLocation" class="btn btn-light">Use My Current Location</button>
    <script src="<%= asset_path('geolocation.js.erb') %>"></script>
</div>